language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install cppcheck pcre2; fi

script:
  - cd $TRAVIS_BUILD_DIR/src && ./configure && make && make ct-test
  - cppcheck ./ --enable=all -q
