language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

os:
  - linux
  - osx

install:
  - pip3 install pylint pytest PyYAML

script:
  - echo hi | ./ct
  - pylint chromaterm/
  - pytest chromaterm/
